security.jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEphdmFDaGF0IGJhY2tlbmQgc2VjcmV0

spring.flyway.enabled=true
spring.flyway.schemas=chat
spring.flyway.locations=classpath:db/migration

spring.datasource.url=jdbc:postgresql://db:5432/javachat
spring.datasource.username=postgres
spring.datasource.password=password
